CI: Attempt to publish test reports - Publish report in case of failure

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -36,11 +36,13 @@ jobs:
         run: ./gradlew build
 
       - name: Copying test reports
+        if: success() || failure()    # run this step even if previous step failed
         run: |
           mkdir test-reports
           cp -R elaastic-questions-server/build/reports/tests/* test-reports
 
       - name: Uploading test reports
+        if: success() || failure()    # run this step even if previous step failed
         uses: actions/upload-artifact@v2
         with:
           name: Test-reports
